artifact_uri: file:///home/greg/complori_task/notebooks/mlruns/0/1db815ae0bfd45638394c6de884b9332/artifacts
end_time: 1692031359467
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1db815ae0bfd45638394c6de884b9332
run_uuid: 1db815ae0bfd45638394c6de884b9332
source_name: ''
source_type: 4
source_version: ''
start_time: 1692031018895
status: 3
tags: []
user_id: greg
