artifact_uri: file:///home/greg/complori_task/notebooks/mlruns/0/4d38ff73071d4ff18bc7dfe01e7113c0/artifacts
end_time: 1692082933156
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 4d38ff73071d4ff18bc7dfe01e7113c0
run_uuid: 4d38ff73071d4ff18bc7dfe01e7113c0
source_name: ''
source_type: 4
source_version: ''
start_time: 1692037396112
status: 3
tags: []
user_id: greg
