artifact_uri: file:///home/greg/complori_task/notebooks/mlruns/0/21f33f7e975749c1a4fc280bf927a1ab/artifacts
end_time: 1692030849266
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 21f33f7e975749c1a4fc280bf927a1ab
run_uuid: 21f33f7e975749c1a4fc280bf927a1ab
source_name: ''
source_type: 4
source_version: ''
start_time: 1692030572169
status: 3
tags: []
user_id: greg
